//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class capitulo
    {
        public int id_capitulo { get; set; }
        public Nullable<int> nro_capitulo { get; set; }
        public Nullable<int> id_temporada { get; set; }
        public Nullable<int> id_video { get; set; }
    
        public virtual temporada temporada { get; set; }
        public virtual video video { get; set; }
    }
}
