//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contenidos_multimedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public contenidos_multimedia()
        {
            this.contenido_multimedia_generos = new HashSet<contenido_multimedia_generos>();
            this.temporadas = new HashSet<temporada>();
            this.perfil_favoritos = new HashSet<perfil_favoritos>();
        }
    
        public int id_contenido_multimedia { get; set; }
        public Nullable<int> edad_clasificacion { get; set; }
        public Nullable<int> anho_publicacion { get; set; }
        public string director { get; set; }
        public Nullable<int> id_video { get; set; }
        public Nullable<int> id_tcontenido_multimedia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contenido_multimedia_generos> contenido_multimedia_generos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temporada> temporadas { get; set; }
        public virtual tipos_contenido_multimedia tipos_contenido_multimedia { get; set; }
        public virtual video video { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<perfil_favoritos> perfil_favoritos { get; set; }
    }
}
