//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado_actividades
    {
        public int id_estado_actividad { get; set; }
        public Nullable<decimal> volumen { get; set; }
        public Nullable<decimal> segundo_reproduccion { get; set; }
        public Nullable<decimal> velocidad { get; set; }
        public Nullable<int> id_perfil_actividad { get; set; }
        public Nullable<int> id_audio { get; set; }
        public Nullable<int> id_subtitulo { get; set; }
    
        public virtual audio audio { get; set; }
        public virtual perfil_actividades perfil_actividades { get; set; }
        public virtual subtitulo subtitulo { get; set; }
    }
}
