//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netflixdbEntities : DbContext
    {
        public netflixdbEntities()
            : base("name=netflixdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<audio> audios { get; set; }
        public virtual DbSet<capitulo> capitulos { get; set; }
        public virtual DbSet<contenido_multimedia_generos> contenido_multimedia_generos { get; set; }
        public virtual DbSet<contenidos_multimedia> contenidos_multimedia { get; set; }
        public virtual DbSet<cuenta_perfiles> cuenta_perfiles { get; set; }
        public virtual DbSet<cuenta> cuentas { get; set; }
        public virtual DbSet<estado_actividades> estado_actividades { get; set; }
        public virtual DbSet<genero> generos { get; set; }
        public virtual DbSet<idioma> idiomas { get; set; }
        public virtual DbSet<pais> paises { get; set; }
        public virtual DbSet<perfil_actividades> perfil_actividades { get; set; }
        public virtual DbSet<perfil_favoritos> perfil_favoritos { get; set; }
        public virtual DbSet<perfile> perfiles { get; set; }
        public virtual DbSet<plane> planes { get; set; }
        public virtual DbSet<propietario> propietarios { get; set; }
        public virtual DbSet<subtitulo> subtitulos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<temporada> temporadas { get; set; }
        public virtual DbSet<tipos_contenido_multimedia> tipos_contenido_multimedia { get; set; }
        public virtual DbSet<video_audios> video_audios { get; set; }
        public virtual DbSet<video_subtitulos> video_subtitulos { get; set; }
        public virtual DbSet<video> videos { get; set; }
    }
}
