//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plane()
        {
            this.cuentas = new HashSet<cuenta>();
        }
    
        public int id_plan { get; set; }
        public string nombre { get; set; }
        public Nullable<decimal> costo_mensual { get; set; }
        public Nullable<int> cant_disp_simult { get; set; }
        public Nullable<int> cant_disp_desc { get; set; }
        public Nullable<bool> contenido_ilimitado { get; set; }
        public Nullable<bool> multi_plataforma { get; set; }
        public Nullable<bool> hd_disponible { get; set; }
        public Nullable<bool> uhd_disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuenta> cuentas { get; set; }
    }
}
