//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_audios
    {
        public int id_video_audio { get; set; }
        public Nullable<int> id_audio { get; set; }
        public Nullable<int> id_video { get; set; }
    
        public virtual audio audio { get; set; }
        public virtual video video { get; set; }
    }
}
